export const DISABLED = 'disabled'
export const ARIA_HIDDEN = 'aria-hidden'
export const DATA_ACTIVE = 'data-active'
export const TAB_INDEX = 'tabindex'
export const TRUE = 'true'
export const FALSE = 'false'