name: Publish BudgetApp to Azure

on: 
  workflow_dispatch:
  push:
    branches:
      -main
jobs:
  publish:
    runs-on: unbuntu-latest

    steps: 
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore
        run: dotnet restore ./BudgetApp.sln

      - name: Build
        run: dotnet build ./BudgetApp.sln --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish ./BudgetApp.sln --configuration Release --no-build
        
